### ISSUE TITLE
`addOOO` should not update Base index

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-db2#395]
> In general if we do add ooo messages then it should not update this index.

From https://github.com/ssbc/ssb-ebt/pull/72#issuecomment-1274832766

Same should happen with addTransaction because it uses addOOO under the hood, I suppose.

**Comment by arj03** [comment]
I have been thinking about this and here is a dump of my notes. 

We need to avoid duplicates in the database. Base index takes care of EBT for us. Index replication needs to do a check as well. And then we have addooo in db2 that checks the database for duplicates before inserting. So far so good, sadly there is another really tricky case with base index and EBT where we switch from index replication to full replication. For this to work to we need some way for know that a feed is in a partial state and delete those partial messages before doing normal full replication. Otherwise we will also have duplicates. So of this smells like a ton of corner cases.

In db1 there was only 1 type of ooo, In a thread you could fetch messages from outside your hops. And those would be stored in a separate db. The messages in this db was never part of any indexes. Iirc you just checked in the db given the msg key if you were missing a message.

Another way to solve this whole thing is to store these ooo messages in a separate log. This log could have jitdb indexes. I'm not entirely sure what the best API would be, if we need it in db2 where it checks in the main db first and then falls back the ooo db afterwards. Or of we say that these ooo messages are used in very specific places: metafeeds, about, threads(maybe?) That those modules could do the extra query. In any case it is not really a bit problem that we have messages in both databases. And this would make things a lot easier to reason about. Secondly an index like base would never know about this ooo db.

**Comment by staltz** [comment]
> If it removes the ooo flag on seeing a msg with seq 1 then i think the "switch from partial to full" should be crash safe.

Nice optimization.

A new question: what was the reason why we can't messages stored in the wrong order? Suppose I'm replicating Alice's messages out of order, msg5, msg1, msg3. Then, I decide to switch to full replication, and I can just replicate msg2, msg4, and add them to the log, so I end up with this order: msg5, msg1, msg3, msg2, msg4. Then, when we call getAtSequence, ssb-db2 just does the leveldb lookup for `[aliceId, sequence]`, it spits out an `offset`, and then I pass that to the remote EBT peer.

Would we *have* to delete Alice's OOO messages and refetch them "in order"?

**Comment by arj03** [comment]
Well you could just fetch what you need, but then EBT needs to know what you have or do that another way. Much easier to delete and use the EBT hammer 🙂

**Comment by staltz** [comment]
> Well you could just fetch what you need, but then EBT needs to know what you have or do that another way. Much easier to delete and use the EBT hammer slightly_smiling_face

Yeah, before I saw your reply I was typing this:

> Then, I decide to switch to full replication, and I can just replicate msg2, msg4

I'm thinking how this would play out in practice. I assume that when we switch to full replication for Alice's feed, that just means doing normal `classic` EBT format replication. But we could change `classic` EBT format such that it checks `base` index, and if `base` index says that alice is in OOO mode, then we can just tell the remote EBT peer that we want to replicate all of alice's feed from seq 1 onwards, except when we get the messages, we just check with `getAtSequence` whether we have it already or not, and skip adding the ones we already have (maybe just removing the `.ooo` field from them).

I'm not sure what this would look like in terms of performance.

**Comment by arj03** [comment]
I can take this one, the task seems to be well specified
