### ISSUE TITLE
Middleware to handle decryptors and validators

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-db2#45]
This is still a vague architectural idea, but given that we'll soon have private message/group support, might be worth discussing how to structure the code.

Would be good to create an architecture or pattern for these modules that need to do some processing "in between", as opposed to hard coding those. A middleware architecture similar to `express` or `secret-stack` that allows installing modules would be good. Each of these middleware modules would (conceptually)  be simply a function that receives some input (the currently processed data) and asynchronously returns output to allow the next middleware to run. Maybe there should be a way of saying which of those apply serially and which apply in parallel.

What I'm thinking right now is how to handle validation with better performance, possibly using Node's `worker_threads` or in the browser using WebWorkers.

I heard that ssb-private1 and ssb-private2 have these boxers that can be added, and thought it could fit the middleware pattern.

cc @arj03 @mixmix

**Comment by arj03** [comment]
Yes this is the approach I'm thinking for private. I'm still in the middle of testing it out. Private groups are a bit different in that they can changes to something you already handled before. But yes I think that this appraoch might be good also for validate.

**Comment by arj03** [comment]
Preliminary results are encouraging. Adding this private layer adds a constant overhead, meaning the overhead is the same if 1 or 2 indexes run at the same time. Furthermore running one and then a second index means that the overhead for the second is basically zero.

**Comment by mixmix** [comment]
Dominic was very keen for these middleware processors for private messages to be synchronous. This stops people being able to write code which is doing eg disk i/o which should slow things down a lot. The requirement then forces you to have a concept of "ready" which means you zany start trying unboxing to ask unboxers have loaded all the state they need (in this case group keys into memory).

Honestly i don't know if I like this opinion having built with it. The onReady code cab get really fidely. And sometimes I'm worried about race conditions...

Another thing to note with the unboxer middleware is that it behaves like a router - first one to succeed wins. So order you load middleware matters. This isn't such a concern for unboxers but it is for boxers because private1 and tribes (private2) have overlap when it comes to handling DMs.

**Comment by staltz** [comment]
I think we have other ways of keeping people from writing heavy stuff in middlewares

Gonna comment more later

**Comment by mixmix** [comment]
Yeah like education, or maybe social shaming for authors if modules which don't pass a benchmark?

**Comment by staltz** [comment]
I believe feedFormats and encryptionFormats is essentially this idea.
